services:
  # TODO web

  db:
    #postgres 
    image: postgres:latest # image using
    restart: unless-stopped # restart container if stoppedj
    hostname: milestone-1-db # hostname of container
    ports:  #exposed port
      - 5434:5432 # host:container
    env_file: # environment
      - .env
    volumes: 
      - ./data:/var/lib/postgresql/data
volumes:
    data:
# TODO
